const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

// A DiffReport is generated when two Contracts are compared.
// It stores the full structured diff plus severity summary.
const DiffReport = sequelize.define('DiffReport', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  projectId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'project_id',
    references: { model: 'projects', key: 'id' },
    onDelete: 'CASCADE',
  },
  oldContractId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'old_contract_id',
    references: { model: 'contracts', key: 'id' },
  },
  newContractId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'new_contract_id',
    references: { model: 'contracts', key: 'id' },
  },
  // Counts for quick dashboard display
  breakingCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    field: 'breaking_count',
  },
  warningCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    field: 'warning_count',
  },
  safeCount: {
    type: DataTypes.INTEGER,
    defaultValue: 0,
    field: 'safe_count',
  },
  overallSeverity: {
    type: DataTypes.ENUM('SAFE', 'WARNING', 'BREAKING'),
    defaultValue: 'SAFE',
    field: 'overall_severity',
  },
  // The actual structured diff — array of change objects
  diffResult: {
    type: DataTypes.JSON,
    allowNull: false,
    field: 'diff_result',
    comment: 'Array of { path, changeType, oldValue, newValue, severity }',
  },
  // Human-readable text report (generated by reportGenerator service)
  humanReadableReport: {
    type: DataTypes.TEXT('long'),
    allowNull: true,
    field: 'human_readable_report',
  },
  webhookFired: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    field: 'webhook_fired',
  },
  webhookFiredAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'webhook_fired_at',
  },
});

module.exports = DiffReport;